# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import random

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_window(object):
    def setupUi(self, window):
        window.setObjectName("window")
        window.resize(701, 486)
        self.centralwidget = QtWidgets.QWidget(window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 501, 401))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.butt8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.butt8.setEnabled(False)
        self.butt8.setFocusPolicy(QtCore.Qt.NoFocus)
        self.butt8.setObjectName("butt8")
        self.gridLayout.addWidget(self.butt8, 2, 1, 1, 1)
        self.butt7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.butt7.setEnabled(False)
        self.butt7.setFocusPolicy(QtCore.Qt.NoFocus)
        self.butt7.setObjectName("butt7")
        self.gridLayout.addWidget(self.butt7, 2, 0, 1, 1)
        self.butt5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.butt5.setEnabled(False)
        self.butt5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.butt5.setObjectName("butt5")
        self.gridLayout.addWidget(self.butt5, 1, 1, 1, 1)
        self.butt2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.butt2.setEnabled(False)
        self.butt2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.butt2.setObjectName("butt2")
        self.gridLayout.addWidget(self.butt2, 0, 1, 1, 1)
        self.butt1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.butt1.setEnabled(False)
        self.butt1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.butt1.setObjectName("butt1")
        self.gridLayout.addWidget(self.butt1, 0, 0, 1, 1)
        self.butt4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.butt4.setEnabled(False)
        self.butt4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.butt4.setObjectName("butt4")
        self.gridLayout.addWidget(self.butt4, 1, 0, 1, 1)
        self.butt3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.butt3.setEnabled(False)
        self.butt3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.butt3.setObjectName("butt3")
        self.gridLayout.addWidget(self.butt3, 0, 2, 1, 1)
        self.butt6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.butt6.setEnabled(False)
        self.butt6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.butt6.setObjectName("butt6")
        self.gridLayout.addWidget(self.butt6, 1, 2, 1, 1)
        self.butt9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.butt9.setEnabled(False)
        self.butt9.setFocusPolicy(QtCore.Qt.NoFocus)
        self.butt9.setObjectName("butt9")
        self.gridLayout.addWidget(self.butt9, 2, 2, 1, 1)
        self.butt_generate = QtWidgets.QPushButton(self.centralwidget)
        self.butt_generate.setGeometry(QtCore.QRect(560, 340, 93, 28))
        self.butt_generate.setObjectName("butt_generate")
        self.verticalSlider = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider.setGeometry(QtCore.QRect(590, 80, 22, 251))
        self.verticalSlider.setMinimum(5)
        self.verticalSlider.setMaximum(10)
        self.verticalSlider.setSliderPosition(7)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setInvertedAppearance(True)
        self.verticalSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.verticalSlider.setObjectName("verticalSlider")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(550, 30, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(560, 380, 93, 28))
        self.pushButton.setObjectName("pushButton")
        window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(window)
        self.statusbar.setObjectName("statusbar")
        window.setStatusBar(self.statusbar)

        self.retranslateUi(window)
        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslateUi(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("window", "Password generator"))
        self.butt8.setText(_translate("window", "0"))
        self.butt7.setText(_translate("window", "0"))
        self.butt5.setText(_translate("window", "0"))
        self.butt2.setText(_translate("window", "0"))
        self.butt1.setText(_translate("window", "0"))
        self.butt4.setText(_translate("window", "0"))
        self.butt3.setText(_translate("window", "0"))
        self.butt6.setText(_translate("window", "0"))
        self.butt9.setText(_translate("window", "0"))
        self.butt_generate.setText(_translate("window", "Generate"))
        self.label.setText(_translate("window", "Count of points"))
        self.pushButton.setText(_translate("window", "Save"))

    def show_result(self):
        list = generate(self.verticalSlider.value())
        print(list)
        pass


def generate(length):
    generation_length = length if length < 10 else random.randint(5, 9)
    restrictions = {1: [(3, 2), (7, 4), (9, 5)],
                    2: [(8, 5)],
                    3: [(1, 2), (7, 5), (9, 6)],
                    4: [(6, 5)],
                    5: [(-1, -1)],
                    6: [(4, 5)],
                    7: [(1, 4), (3, 5), (9, 8)],
                    8: [(2, 5)],
                    9: [(1, 5), (3, 6), (7, 8)]}
    allowed = [i for i in range(1, 10)]
    random.shuffle(allowed)
    allowed = allowed[:generation_length]
    result = []

    result.append(allowed.pop())

    while any(allowed):
        next_number = allowed.pop()
        potential_restriction = restrictions.get(next_number)
        for k, v in potential_restriction:
            if result[-1] == k and v not in result and v in allowed:
                result.append(v)
                allowed.remove(v)
        result.append(next_number)

    return result



def run():
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = QtWidgets.QMainWindow()
    ui = Ui_window()
    ui.setupUi(window)
    window.show()
    ui.butt_generate.clicked.connect(ui.show_result)
    app.exec_()
    # sys.exit(app.exec_())

if __name__ == "__main__":
    run()